CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:MdPX7e5LF+dGYsg1zLeXbfbqaW555w/wbMUZKD2Yqg/ZUa+q0S1Z8ehb4O7pX32/3YBzhKM=,iv:QfOW6Pv8fWAugkC4HutCBlSPEVWHStZQDQFokykOqI0=,tag:X1T5o8rFGK1xOauUh+6lmw==,type:str]
sops:
    age:
        - recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMjBFVkRGUFBsaFVIN0dJ
            Qi9LbGxrVWJBRDE4UDNyL0NXWnVKdW9HVXo4CnBhazRWMU1ta3M5MzlIYzU5UEt1
            c2F6b1JnRkRhRis1V3ExQlpPTjdnVVkKLS0tIEFDWmNXZVBUVzU3TE04eWJQRUZo
            Q0Y4NS9zdlZNQUVKNmdmYWpab3lDOXMK6cPZG+hngABx89HinaXKsTdxHAMo+GKl
            VkNDfOJp8bqJseSc/rIsv2rxfb9SjP3A0rmB+EiUGwbcQgCcYd2/tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T02:58:41Z"
    mac: ENC[AES256_GCM,data:6HuYiGWg7YYWg66VzgC50FqW8GG/K57sdSwrPcyUP5wSekFfvArbeVacJz3TLYAn+pkXLnVMSBc0cimV9i4Mijj+1UulQQ03l4XurmmuMd2e3nY7yWBaPCQCAuyhr3TR5R/Uj5f7bd/th7KV30ZLV+gECK9FO+TZeYdxorzStfs=,iv:n+IDyQunYPTcf3UMj0SqGj2aWoG7S+q1l5APVQAGfQY=,tag:SK7hozzW5KDA+l3MUdnjzw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
