CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:MdPX7e5LF+dGYsg1zLeXbfbqaW555w/wbMUZKD2Yqg/ZUa+q0S1Z8ehb4O7pX32/3YBzhKM=,iv:QfOW6Pv8fWAugkC4HutCBlSPEVWHStZQDQFokykOqI0=,tag:X1T5o8rFGK1xOauUh+6lmw==,type:str]
BETTER_AUTH_SECRET: ENC[AES256_GCM,data:v6DiiRH7nWQaTbJoq2W6URgcJa/GYM0Xlzp4mL/zjXdQXEvbJDiSZiftIiM=,iv:eJ13PZ2B2UxcvWnenjsPjJg1nZzXIk/sQSWFD8gXbsg=,tag:fpYX9BVHBj4h6OoY+AlKLQ==,type:str]
RESEND_API_KEY: ENC[AES256_GCM,data:OV2QocZgSy2yhGkaQnxN9Lg0z3Z9tl3nd6n98imPnR5GxDWU,iv:bFvUVKKPWQwYVIGiUQM5ktCyBVpihUT9PKVTsDXHb5g=,tag:9HUY81UVDpCk8dj7cEVu3Q==,type:str]
sops:
    age:
        - recipient: age1cq0k9s88fmx7kkaqqvuf290lelyt8gkeglwvsd2r3ezuqyla7aps7x4q2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bnJUekhLS0ZmMGZoUy84
            d0RmVHRkVEVkNDdZL0FXUWdqUzIweFNCcVM0CkdDSWU2azNwMGtlbXFoWU5FdWR0
            elVwN1NZLzdWQUhTVUVQYURadWl6MTQKLS0tIE5WWU5JVkhvYTUzbUpuL2NEcEg2
            dmpJYndTSCtJVVpyMzJLWkVxa3hUVDgKBmNFuCu9HlI9q8fuRksP19+hLt+/ZzUD
            4d6Q8lpFn3b9c/3hGFwWd9pPSrd5+J6T/af9pMFSZgi2XlrHw9Lt7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age125sdujhaks4ezxrk9p4uaxmhmqau0rwqwv0dtc6qal4vl8xuav4sgrfvdc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTGROMmdyeUNQZ0QvQ2cw
            QS90Ny85cC83b0N2emFMQVpaWkpSYWIycFJvCjlRRkExb1ZqRUF3RTlydFhoRDJX
            K1EyaG1iUk9oS1AzYUtzZ0RUSGtrQk0KLS0tIHcxUnZER2hNR0xwK09FVWx6ZW1i
            SXkxTTFzeWtuWUllWUxqa3l0cEdJYUEKXYzRMcKHTW6qplABvsl1Ig1/qFoo9hen
            BwAAKFjM1O5b3e9ocxxgL64RoP42k73rAutpcT9GKKncwh4MyNf8+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age104ck7dcan0pd9z3h73skusp0g9anh59ummu2ddg0dyf4fl74x57q0yhwuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISDN5MFl5VTgwVTB1dUYx
            YlQ1UGkrZWFGbU56QnR3RS9HN0cvekI5MkRRCnB1MlB4SGpYS3VVY1BuTjFkUmg0
            K2VydUh2WTRENjRmOFlmYStwcEgyWXMKLS0tIHRLVXYwMlY4MVhqWjVwT1lxRmdS
            VDhhYUxWUDFQd3dWVXA5QUNoZnU1c00KVGIhSWQAhZR36zTq7ccm0vfeq2uFNdte
            L81RjfmpmjK0dPkSK6Ah6CwgrLpG7Ie4tk/2nzbcgVlXmJHginKHKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dhslnakk54dn5vd7q7hjuemrchwxtka0ux8nkvm4psp9u3g9hsxsjzvsdz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUVkzdjdxVmljM041ZDdM
            M0xMUnJJaDY4M1J5TDVmZThOaExXSkJvRkZ3CjRac0U3RVBhc2hCQ3k3UGhJc2Mv
            WTBJcmdJNU55VkU3bUZYSjZFcEp0clEKLS0tIHQ2Sk15QUh5ZTFhbDFTNTUwK0h4
            RDdudURMNm9IZW85dkEvWHBscWJMNUEKX5UV5GcI08Xp9EsHCJcwP/D0srTlfD3S
            Kn2X2eHc2iehjYB0K7st+A0qA1FUb8I5A1TPH4tC5PpMPLd5iTGScQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-27T00:40:34Z"
    mac: ENC[AES256_GCM,data:BSCBvSbST9poBwZH3hYltXXBBGSCxWgNCe3KfZe6zc7JGHyEWVeK1oJUtEDna4lFE1o/Z0G7P6TgcG+bVBf/8UJP806XBnVINEOct7yGUzgOK6jaYTqjsRf8DxEHD1GkgHLUWcRKQqTP9KqgSyIlgJKN/OJJCxjELJZyMYaATV4=,iv:qsGVXNY0x//z3AgYpSnn1QVVUIWIUZE5anekCjChCVQ=,tag:4bkd/xI5RinQjIdB6uD5gA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
