#!/usr/bin/env bun
/**
 * Derive the doc tree at build time (ADR-0005).
 *
 * A Worker has no working tree, so the cloud deployment cannot walk README on
 * read the way `docs:check` and local development do. It runs the *same* walker
 * here instead and emits its output into the bundle. There is still exactly one
 * walker: this script imports `@crux/core/docs` and adds no traversal of its
 * own — it only expands each reachable doc and writes the result out.
 *
 * Structural rot fails the build, naming the broken links and orphans, so a
 * deployment can never serve a doc tree the rot check would reject.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { expandDoc, findRepoRoot, formatRot, hasRot, ROOT_DOC, walkDocs } from "@crux/core/docs";

const repoRoot = findRepoRoot();
const out = join(repoRoot, "apps/cloud/src/generated/docs-tree.ts");

const { reachable, rot } = walkDocs(repoRoot);

if (hasRot(rot)) {
  console.error(formatRot(rot));
  console.error("\nStructural rot — refusing to build a doc tree the rot check rejects.");
  process.exit(1);
}

/** Every reachable doc, with its `@import`s already inlined. */
const docs = Object.fromEntries(
  reachable.map((path) => [
    path,
    expandDoc(repoRoot, path)
      .map((s) => s.source)
      .join(""),
  ]),
);

const banner = `/**
 * GENERATED by scripts/build-docs.ts — do not edit.
 *
 * The README-rooted doc tree of the commit this Worker was built from, walked by
 * @crux/core/docs and with every \`@import\` inlined (ADR-0005).
 */`;

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `${banner}
export const DOCS_ROOT = ${JSON.stringify(ROOT_DOC)};
export const DOCS: Record<string, string> = ${JSON.stringify(docs, null, 2)};
`,
);

console.log(`docs: ${reachable.length} reachable docs → ${out.slice(repoRoot.length + 1)}`);
