#!/usr/bin/env bun
/**
 * Render `/favicon.ico` from the mark, and write it out as a source module.
 *
 * Run this whenever `MARK_SVG` in `apps/cloud/src/web/brand.ts` changes:
 *
 *     bun run favicon
 *
 * Deliberately *not* part of `bun run build`. The doc tree is generated on
 * every build because its walker is pure TypeScript and CI already has it; this
 * needs `rsvg-convert` and `magick`, and putting those on the deploy path would
 * mean a missing apt package can stop a release. The mark changes about never,
 * so the cost of committing the output — that it can drift from `MARK_SVG` if
 * someone edits the drawing and forgets this — is the cheaper of the two, and
 * `--check` exists to catch exactly that drift.
 *
 * The ICO carries 16 and 32 px entries and stops there. ImageMagick writes ICO
 * entries as uncompressed BMP, so a 48px entry costs ~10KB on its own — nearly
 * three times the rest of the file — and buys only Windows site-pinning, which
 * nothing here uses. Modern browsers take `/favicon.svg` regardless; this file
 * exists for Safari and for browsers old enough not to read SVG at all.
 *
 * `rsvg-convert` rasterises each size from the vector rather than downsampling
 * one big bitmap, so the 16px entry — the one a tab strip actually shows — is
 * rendered at its real size instead of being a blurred shrink of the 32.
 */
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { MARK_SVG } from "../apps/cloud/src/web/brand.ts";

const OUT = new URL("../apps/cloud/src/web/favicon-ico.ts", import.meta.url).pathname;
const SIZES = [16, 32];
const check = process.argv.includes("--check");

function need(bin: string): void {
  try {
    execFileSync("command", ["-v", bin], { shell: "/bin/sh", stdio: "ignore" });
  } catch {
    console.error(`build-favicon: \`${bin}\` is not on PATH. On macOS: brew install imagemagick librsvg`);
    process.exit(1);
  }
}
need("rsvg-convert");
need("magick");

const work = mkdtempSync(join(tmpdir(), "crux-favicon-"));
try {
  const svg = join(work, "mark.svg");
  writeFileSync(svg, MARK_SVG);

  const pngs = SIZES.map((s) => {
    const png = join(work, `${s}.png`);
    execFileSync("rsvg-convert", ["-w", String(s), "-h", String(s), svg, "-o", png]);
    return png;
  });

  const ico = join(work, "favicon.ico");
  execFileSync("magick", [...pngs, ico]);
  const base64 = readFileSync(ico).toString("base64");

  const module = `/**
 * GENERATED by scripts/build-favicon.ts — do not edit by hand.
 *
 * The ${SIZES.join("/")} px ICO rendered from \`MARK_SVG\` in ./brand.ts, base64'd because
 * the Worker has no filesystem and this deployment has no assets binding. Edit
 * the mark there, then run \`bun run favicon\` to bring this back into agreement.
 */
export const FAVICON_ICO_BASE64 =
  "${base64}";
`;

  if (check) {
    const current = (() => {
      try {
        return readFileSync(OUT, "utf8");
      } catch {
        return "";
      }
    })();
    if (current !== module) {
      console.error(
        "build-favicon: favicon-ico.ts is out of date with MARK_SVG. Run `bun run favicon`.",
      );
      process.exit(1);
    }
    console.log("favicon: favicon-ico.ts matches MARK_SVG");
  } else {
    writeFileSync(OUT, module);
    console.log(`favicon: ${SIZES.join("/")}px ICO (${base64.length} b64 chars) → ${OUT}`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
